---
# tasks file for gitlab-runner-role
- name: Update apt packages
  ansible.builtin.apt:
    upgrade: no
    update_cache: yes

- name: Include Docker task from `common` role
  include_role:
    name: common-role
    tasks_from: setup_docker

- name: Download gitlab-runner
#   ansible.builtin.command: "curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh | sudo bash"
  ansible.builtin.command: curl -LJO "https://gitlab-runner-downloads.s3.amazonaws.com/latest/deb/gitlab-runner_amd64.deb"
- name: Install apt gitlab-runner
  ansible.builtin.command: dpkg -i gitlab-runner_amd64.deb
