---
- name: Setup reverse proxy
  hosts: nginx-pool
  become: true
  handlers:
    - name: Nginx reload
      ansible.builtin.service:
        name: nginx
        state: restarted
  roles:
    - reverse-proxy-role
  post_tasks:
    - name: Apply config for Nginx
      become: true
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: 0644
      notify: Nginx reload
    - name: Apply config for sites
      become: true
      ansible.builtin.template:
        src: default.j2
        dest: /etc/nginx/conf.d/default
        mode: 0644
      notify: Nginx reload
    - name: Request test certs for sites
      become: true
      ansible.builtin.command: /var/lib/snapd/snap/bin/certbot -d www.wedun.ru -m wedun123@yandex.ru --nginx --agree-tos --test-cert
