---
# tasks file for monitoring-role
- name: Update apt packages
  ansible.builtin.apt:
    upgrade: no
    update_cache: yes

- name: Include Docker task from `common` role
  include_role:
    name: common-role
    tasks_from: setup_docker

- name: Include Node exporter task from `common` role
  include_role:
    name: common-role
    tasks_from: setup_node_exporter

- name: Synchronization
  ansible.builtin.copy:
    src: ../files/
    dest: "/opt/stack/"
    owner: root
    group: root
    mode: 0644
  become: true

- name: Pull all images in compose
  ansible.builtin.command: docker-compose -f /opt/stack/docker-compose.yaml pull

- name: Up all services in compose
  ansible.builtin.command: docker-compose -f /opt/stack/docker-compose.yaml up -d
