global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - 'alert.rules'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'vm-1'
    scrape_interval: 10s
    static_configs:
      - targets: [ '10.100.1.23:9100' ]

  - job_name: 'vm-gitlab-1'
    scrape_interval: 10s
    static_configs:
      - targets: [ '192.168.10.26:9100' ]

  - job_name: 'vm-monitor-1'
    scrape_interval: 10s
    static_configs:
      - targets: [ '192.168.10.20:9100' ]

  - job_name: 'vm-app-1'
    scrape_interval: 10s
    static_configs:
      - targets: [ '192.168.10.15:9100' ]

  - job_name: 'vm-db-1'
    scrape_interval: 10s
    static_configs:
      - targets: [ '192.168.10.41:9100' ]

  - job_name: 'vm-db-2'
    scrape_interval: 10s
    static_configs:
      - targets: [ '192.168.10.42:9100' ]